### ISSUE TITLE
sample may fail with null reference on HttpContext.Current

### ISSUE THREAD

**Issue by m-bene** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#17]
When deploying the sample to an azure web role (osfamily 4) it seems to (infrequently/randomly) fail with  a null pointer exception on trying to access HttpContext.Current in the AuthorizationCodeReceived callback.

reloading the page eventually results in successful completion.

Could there be a race condition where it's not guaranteed that HttpContext.Current gets initialized before we try to access it?

currently working around this by using context.Request variables instead of HttpContext - looking good so far.

**Comment by dstrockis** [comment]
@brentschmaltz what do you think of this issue? Does Martin's fix sound reasonable?

**Comment by danny-chou** [comment]
@dstrockis @m-bene I have experienced the same problem recently and is able to resolve it based on your suggestion. 
Thanks!

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups
