### ISSUE TITLE
Log in page doesn't have edit boxes for user name and password

### ISSUE THREAD

**Issue by edcrowson** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#26]
I attempted to log in using credentials for a Windows Live account that is in my AD. The log in failed. I'm fairly confident that the credentials were connect, because I was able to log in the live account just before I attempted to log in to the sample. However, that isn’t the real issue.
The real issue is that since that failed attempt the log in page no longer contains edit boxes for user name or password (see image). I have cleared the cache and restarted my machine but the result is still the same. It is happening inside a library method call. It’s been a while since I did this, but I believe there is a way to get the source needed to step into a DLL like this, but I’m trying to avoid that.
Is this a known issue?
![capture](https://cloud.githubusercontent.com/assets/11528214/6716208/fb6310e0-cd60-11e4-879c-91d7a680ae69.PNG)

**Comment by dstrockis** [comment]
Hey Ed - This seems strange. Would you mind capturing a fiddler trace and sending it over? Feel free to mail me at dastrock@microsoft.com

**Comment by jmprieur** [comment]
Closing the issue.
