### ISSUE TITLE
Revert back to making graph query on server side instead of in Javascript

### ISSUE THREAD

**Issue by skwan** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#28]
Funneling the access token up to the Javascript and making the Graph query from there changes the threat model for the application fairly significantly.  Revert the application to doing the Graph query on the server side so that the access token is not exposed to the browser.  Later, we can build a different sample that does everything in Javascript (with the explicit notion that the threat model is different).

**Comment by jmprieur** [comment]
@kalyankrishna1 : I don't think this is relevant any longer?

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-2-Groups
