### ISSUE TITLE
aspnet50

### ISSUE THREAD

**Issue by elmortega** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#36]
Hi I´m kinda stuck, i need some help in the following issue please.

class GraphHelper expose static methods, this is possible because it relies on class ConfigHelper to get the azure ad configuration info in order to query users thorugh the graph api. This approach works fine in asp.net 4.5 but I´m having trouble using this structure in aspnet50, one of the limitations is that I can´t use the ConfigHelper static approach as ConfigurationManager is not available in aspnet50. I tried to use the IOptions approach, but it's architecture depends on DI and static methods makes no sense this way, I guess I could inject azure ad settings through the controller making the request, but it doesn't feel like a clean solution. I'd appreciate any help on this matter or any examples about authorization based in Azure AD Groups and Roles Claims in aspent50.

**Comment by kalyankrishna1** [comment]
The sample has been completely updated, so closing this issue as these classes have changed.
