### ISSUE TITLE
Update git clone commandline

### ISSUE THREAD

**Issue by flexray** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#37]
Please update git clone commandline in step 1 to groupclaims
git clone https://github.com/Azure-Samples/active-directory-dotnet-webapp-authz-groupclaims.git

now it is 
git clone https://github.com/Azure-Samples/active-directory-dotnet-webapp-authz-roleclaims.git

**Comment by jmprieur** [comment]
Thanks for the feedback. https://github.com/Azure-Samples/active-directory-dotnet-webapp-groupclaims/commit/b9e4f80bbe1cb7f024542af4d40568d42d62ad6e fixed the problem
