### ISSUE TITLE
Very misleading

### ISSUE THREAD

**Issue by Corvin666** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#39]
Good start, but number of issues:
1. The sample fails to explain how roles are set up. When I download the code, I can see authorization attributes as in:  [Authorize(Roles = "Admin, Observer, Writer, Approver")]. How do I assign these roles to user? In my app? In my directory? Do I need to create groups with same names in my AD? Do I need to configure "User assignment required..." in my app on AD portal? If I have multiple apps - does it mean that my groups all pile up in one large groups repository on AD configuration? Some explanation might help.

It becomes clearer, though, as we get to the next issue: 
1. Text states "his sample shows how to build an MVC web application that uses Azure AD Groups for authorization. Authorization in Azure AD can also be done with Application Roles, as shown in WebApp-RoleClaims-DotNet". HOWEVER, the git clone command is THE SAME between the two examples: 
   git clone https://github.com/Azure-Samples/active-directory-dotnet-webapp-authz-roleclaims.git
   which takes the user to "role claims" example. An incorrect repository is referenced in the instructions.

I think it would help if author ran through their example thoroughly before posting this online.

**Comment by jmprieur** [comment]
Thanks for the feedback, @Corvin666. this is now fixed
