### ISSUE TITLE
Failed to acquire token silently as no token was found in the cache

### ISSUE THREAD

**Issue by shwetap051** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#40]
When browsing to Tasks tab on the newly setup web app with the code getting error Failed to acquire token silently as no token was found in the cache. Call method AcquireToken. How to get rid of this error?

**Comment by webstersprodigy** [comment]
Same error here

**Comment by kalyankrishna1** [comment]
The sample has been completely updated, so closing this issue as these steps have changed.
