### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by sameer-kumar** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#41]
When I click Tasks button I get below error:
```
An error occurred while processing your request.
We're having trouble signing you in.

**You do not have sufficient priviliges to view this page.**
```
I followed it end to end.
What I'm missing here?

Thanks!

**Comment by RudyCo** [comment]
I got the same issue, you should also add permissions to the "Windows Azure Active Directory" as per this SO : http://stackoverflow.com/questions/28441216/insufficient-privileges-error-when-trying-to-access-azure-graph-apis
That's being said, the tutorial and documentation about RBAC for ASP.NET are poor so good luck!

**Comment by kalyankrishna1** [comment]
The sample has been completely updated, so closing this issue as these steps have changed.
