### ISSUE TITLE
WebAppGroupClaimsDotNet.mdf missing

### ISSUE THREAD

**Issue by flederflick** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#43]
The WebAppGroupClaimsDotNet.mdf file is missing from the repository. Can I find it somewhere else or is this by design? 

```
<connectionStrings>
    <add name="GroupClaimContext" connectionString="Data Source=(LocalDb)\v11.0;Initial Catalog=WebAppGroupClaimsDotNet;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|\WebAppGroupClaimsDotNet.mdf;" providerName="System.Data.SqlClient" />
  </connectionStrings>
```

**Comment by jmprieur** [comment]
Normally it should be created on the fly.
Which version of VS are you using?

**Comment by flederflick** [comment]
@jmprieur I'm using Visual Studio Community 2017

**Comment by jmprieur** [comment]
@flederflick : then to use localdb, I believe that the connection string would be something like:
```xml
<add name="TodoListServiceContext" connectionString="Data Source=(localdb)\MSSQLLocalDB; Integrated Security=True; MultipleActiveResultSets=True; AttachDbFilename=|DataDirectory|WebAppGroupClaimsDotNet.mdf" providerName="System.Data.SqlClient" />
```
Note that you don't need to use the Initial Catalog
Also you might need to check localdb in the "Individual Components" list in the Visual Studio Installer.

**Comment by flederflick** [comment]
@jmprieur Thanks for your help. That did the trick. changed the name of the connection string you provided to the name already configured in the webconfig and it worked fine.

Thanks for your help

**Comment by jmprieur** [comment]
Thanks for the udate, @flederflick. I'll work on updating this sample.

**Comment by JeremyWard33** [comment]
Hi All, thanks for the pointers no this.   

I was using VS2019 and getting could not create database errors, and finally realized that the folder TodoSPA\App_Data did not exist.  Created that folder and the issue went away.  

Additionally with this change I did not need to add any connectionStrings to the web.config.  

Hope this helps!  :)
