### ISSUE TITLE
Q: How does this use MS Graph when it's referencing AAD Graph?

### ISSUE THREAD

**Issue by RyanTaite** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#44]
I see using statements to `Microsoft.Azure.ActiveDirectory.GraphClient`, which is AAD Graph, and no references to `Microsoft.Graph`, but the readme tells us to add and approve MS Graph permissions?

Even in the code the Graph resource URL is the AAD version: `https://graph.windows.net`; versus the MS Graph version: `https://graph.microsoft.com`

What am I missing here?

**Comment by jmprieur** [comment]
Thanks for your feedback, @RyanTaite . The sample is not using the MS Graph
indeed, you should select "Windows Azure Active Directory" (AAD Graph), not Microsoft Graph. We need to update the README.md

**Comment by kalyankrishna1** [comment]
Sample has been updated to use MS Graph
