### ISSUE TITLE
ClaimHelper.GetGroups "_claim_names" and too many groups edge case

### ISSUE THREAD

**Issue by nkramaric** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#45]
In the following [code](https://github.com/Azure-Samples/active-directory-dotnet-webapp-groupclaims/blob/54d681cd9867f0f0f5846f7e82217fdd65cadc0b/WebApp-GroupClaims-DotNet/Utils/ClaimHelper.cs#L19) there is a check for "_claim_names". What is the purpose of this check? It looks like if _claim_names exists and **has** the property _groups_ then you get groups from the API.

I am looking into this code because I want to make sure I am covering the case when a user has too many groups, see these notes [here](https://cloudblogs.microsoft.com/enterprisemobility/2014/12/18/azure-active-directory-now-with-group-claims-and-application-roles/) and [here](https://stackoverflow.com/questions/45501568/azure-jwt-with-property-hasgroups-true-instead-of-groups-property-object).

Is this something the ClaimHelper currently handles?

Thanks! The sample has been very helpful so far.

**Comment by pothmann** [comment]
Are you refering to the overage limit if user has too many groups?

This is handled in method _Task<List<string>> GetGroupsFromGraphAPI(ClaimsIdentity claimsIdentity)_ in ClaimHelper.

See this [blog post](http://www.dushyantgill.com/blog/2014/12/10/authorization-cloud-applications-using-ad-groups/) where you even find snippets from this very sample.

**Comment by nkramaric** [comment]
Ah OK. I wasn't sure about that _claim_names header and if that was the correct gate for doing the full retrieval from the graph api but reading through that blog post clears it up. Thanks!
