### ISSUE TITLE
Number of group claims returned before "hasGroups"="true"

### ISSUE THREAD

**Issue by Thepriestdude** [Azure-Samples/active-directory-dotnet-webapp-groupclaims#52]
Reading this documentation (section [Groups overage claim](https://github.com/Azure-Samples/active-directory-dotnet-webapp-groupclaims#groups-overage-claim)) gives the impression that the number of groups that can be present in the returned token is 100+, this does no longer seem to be the case, as other sources report the limit is changed to 5. The low number of returned groups thereby force the application to utilize the graphAPI and session storage, calling the graphAPI on the initial visit to extracts the users groups.

An update the the documentation might be in order as to not confuse developers.

Sources:
[Strack overflow, first comment](https://stackoverflow.com/a/45508283)
[Azure-docs discussion](https://github.com/MicrosoftDocs/azure-docs/issues/6996#issuecomment-380631000)
[Another confused user](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/239#issuecomment-314736142)

**Comment by jmprieur** [comment]
@kalyankrishna1 : can you please take care of confirming the change and updating the sample's README.md ?

**Comment by kalyankrishna1** [comment]
@jmprieur noted

**Comment by kalyankrishna1** [comment]
Can you confirm if you are using the [Authorization Code grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code) or the [implicit grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-implicit-grant-flow). The _hasGroups_ claim is only provided in case of the implicit_grant and the number of groups provided in the _groups_ claim is limited to 6 to as more would extend the URI fragment beyond the URL length limits. Refer to the _hasGroups_ and _groups_ claim's documentation in [Azure Active Directory access tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens). This sample is using the openid and authorization code grant.
